name: Step 4, Add Copilot suggestion from comment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE: "path/to/your/file"
      SEARCH: "search_string"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run your script
      run: |
        echo "Check that all required env variables are set"
        if [ -z "$FILE" ]; then
          echo "FILE is unset or set to the empty string"
          exit 1
        fi
        if [ -z "$SEARCH" ]; then
          echo "SEARCH is unset or set to the empty string"
          exit 1
        fi
        if ! grep -q "$SEARCH" "$FILE"; then
          echo "Missing $SEARCH in $FILE"
          echo "----------------"
          cat "$FILE"
          exit 204
        fi
